/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./shared/components/base-button/BaseButton.vue')['default']
    BaseColumn: typeof import('./shared/components/base-table/BaseColumn.vue')['default']
    BaseTable: typeof import('./shared/components/base-table/BaseTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BaseButton: typeof import('./shared/components/base-button/BaseButton.vue')['default']
  const BaseColumn: typeof import('./shared/components/base-table/BaseColumn.vue')['default']
  const BaseTable: typeof import('./shared/components/base-table/BaseTable.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}